using System;
using System.Collections.Generic;
using System.Text;

namespace ContentCreator
{
    public enum Effects
    {
        LOSE_HP,
        GAIN_HP,
        LOSE_AP,
        GAIN_AP,
        LOSE_MP,
        GAIN_MP,
        LOSE_RANGE,
        GAIN_RANGE,
        LOSE_INVOC,
        GAIN_INVOC,
        LOSE_SHIELD,
        GAIN_SHIELD,
        LOSE_RET_MP,
        GAIN_RET_MP,
        LOSE_RET_AP,
        GAIN_RET, AP,
        LOSE_DODGE_MP,
        GAIN_DODGE_MP,
        LOSE_DODGE_AP,
        GAIN_DODGE_AP,
        LOSE_RES_EARTH,
        GAIN_RES_EARTH,
        LOSE_RES_WATER,
        GAIN_RES_WATER,
        LOSE_RES_AIR,
        GAIN_RES_AIR,
        LOSE_RES_FIRE,
        GAIN_RES_FIRE,
        LOSE_RES_LIGHT,
        GAIN_RES_LIGHT,
        LOSE_RES_DARK,
        GAIN_RES_DARK,
        LOSE_CARAC_EARTH,
        GAIN_CARAC_EARTH,
        LOSE_CARAC_WATER,
        GAIN_CARAC_WATER,
        LOSE_CARAC_AIR,
        GAIN_CARAC_AIR,
        LOSE_CARAC_FIRE,
        GAIN_CARAC_FIRE,
        LOSE_CARAC_LIGHT,
        GAIN_CARAC_LIGHT,
        LOSE_CARAC_DARK,
        GAIN_CARAC_DARK,
        GAIN_HEAL,
        LOSE_HEAL,
        PUSH,
        PULL,
        TELEPORT,
    }
}
